// SPDX-License-Identifier: MIT
pragma solidity ^0.8.34;

import {Test, console} from "forge-std/Test.sol";
import {HCAAccount} from "../src/HCAAccount.sol";
import {FalconVerifier} from "../src/verifiers/FalconVerifier.sol";
import {ZKNOX_ethfalcon} from "../lib/ETHFALCON/src/ZKNOX_ethfalcon.sol";
import {UserOperation} from "../src/interfaces/IAccount.sol";

/// @notice End-to-end Falcon test: HCA flow with FalconVerifier using the
///         4-param ETHFALCON verify path. Test vector generated by
///         falcon_service.py sign <seed> <msg> where
///             seed = 0x11 * 48
///             msg  = 0xCC * 32
contract FalconE2ETest is Test {
    address constant ENTRY_POINT = 0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789;

    ZKNOX_ethfalcon public engine;
    FalconVerifier public falconVerifier;

    function setUp() public {
        engine = new ZKNOX_ethfalcon();
        falconVerifier = new FalconVerifier(address(engine));
    }

    function test_FalconE2E() public {
        bytes32 msgHash = bytes32(0xcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc);
        (uint256[] memory ntth, uint256[] memory s2, bytes memory salt) = _buildVector();

        // 1. Commitment = abi.encode(uint256[] pkCompact)
        bytes memory commitment = abi.encode(ntth);

        // 2. Leaf hash = keccak256(version || keccak256(commitment))
        uint8 version = 0x02; // Falcon
        bytes32 leafHash = keccak256(abi.encodePacked(version, keccak256(commitment)));

        // 3. Build a 2-leaf tree (dummy sibling) so we exercise the Merkle path
        bytes32 dummyLeafHash = keccak256("dummy-sibling");
        bytes32 authRoot = keccak256(abi.encodePacked(leafHash, dummyLeafHash));

        // 4. Deploy HCA account with Falcon verifier registered
        HCAAccount account = _deployAccount(authRoot);

        // 5. sigData = abi.encode(bytes salt, uint256[] s2, uint256[] ntth)
        bytes memory sigData = abi.encode(salt, s2, ntth);

        // 6. Merkle proof = [dummySibling]
        bytes32[] memory proof = new bytes32[](1);
        proof[0] = dummyLeafHash;

        // 7. Full 5-field signature
        bytes memory fullSig = abi.encode(version, uint256(0), proof, commitment, sigData);

        UserOperation memory userOp = _buildUserOp(address(account), fullSig);

        vm.prank(ENTRY_POINT);
        uint256 result = account.validateUserOp(userOp, msgHash, 0);
        assertEq(result, 0, "Falcon validateUserOp should succeed");
    }

    function _deployAccount(bytes32 authRoot) internal returns (HCAAccount) {
        uint8[] memory versions = new uint8[](1);
        versions[0] = 0x02;
        address[] memory verifierAddrs = new address[](1);
        verifierAddrs[0] = address(falconVerifier);

        HCAAccount account = new HCAAccount(authRoot, ENTRY_POINT, address(this), versions, verifierAddrs);
        vm.deal(address(account), 1 ether);
        return account;
    }

    function _buildUserOp(address sender, bytes memory sig) internal pure returns (UserOperation memory) {
        return UserOperation({
            sender: sender,
            nonce: 0,
            initCode: "",
            callData: "",
            callGasLimit: 500000,
            verificationGasLimit: 5000000,
            preVerificationGas: 100000,
            maxFeePerGas: 1 gwei,
            maxPriorityFeePerGas: 1 gwei,
            paymasterAndData: "",
            signature: sig
        });
    }

    function _buildVector() internal pure returns (uint256[] memory ntth, uint256[] memory s2, bytes memory salt) {
        ntth = new uint256[](32);
        ntth[0]  = 0x0d7f177c16af26650c900cab27692a9d1b0728be25a009d10166155d05160209;
        ntth[1]  = 0x2f852aba02d40f651a8d04fa0cf412792e1612e9017214a41a7a0f2723e0084e;
        ntth[2]  = 0x0feb0cf718210f0b27de184503642152068d21722ac90cdb18a50e92155c2460;
        ntth[3]  = 0x1f5824202bba043414e906e3146322d30a9d216326a02840040a248728fe02d8;
        ntth[4]  = 0x25680fee2bd62f852ab60eb009fc09d312380655069f2ffb1b120cdf1aff1c35;
        ntth[5]  = 0x0ebc2f0402dd294406e82dfe2a281153128e06c81e170b0f014906c41f081df7;
        ntth[6]  = 0x0dbc0695084a161607d7060b156c2203130024870fba2d5a276515d2020100e8;
        ntth[7]  = 0x26662ad1028e2afc241510c3120d22ed296424e22bb72a1104202be3161d0620;
        ntth[8]  = 0x023a2877119420a612d71dc00158007d1bb62fe50cd011a022ab0aed16cb0152;
        ntth[9]  = 0x052d008f2a1d1af0234d2e532489231a2dec098b20b205e809611c161b781221;
        ntth[10] = 0x1c730aee23c92d4a00db227015ea0feb16ba1e1729831a7f2b07038b1e3b0391;
        ntth[11] = 0x272701cc2f8917df228213e008fc0e371a76298612222a0f046e0e1e172d07d9;
        ntth[12] = 0x029f14da0e960050288a02452e612d892e9b1d9a08741250298228430dd81354;
        ntth[13] = 0x068b03a92c31271c0c8f257c047f2a4204b51ca2007a03391bec2bdb04c31065;
        ntth[14] = 0x1361270e09c4048f14a0015b205425a915871924164204ff163611470e7c0ff3;
        ntth[15] = 0x0e7b090a09272f022aea04220d5a2b04094c22c907300bc61fb112a607620190;
        ntth[16] = 0x0e04132906e408fc1601235c25ce219c278f2fdd07a40c5709a627a320dc1e9e;
        ntth[17] = 0x13a41fc61813166e13f502f315b9028f20091510296023d102ea0f2326561fc5;
        ntth[18] = 0x08560e582a460bb7051e0206122d1664117820e514b3150c11532b8b1fad257d;
        ntth[19] = 0x22fb0f46027605570c832db72e8b0d7a0094273d2fee14ee194503a517b929a1;
        ntth[20] = 0x11ff22c324a313900d762196290616020ef907221f9b265723af12db2fad2f3f;
        ntth[21] = 0x1b9d1ee429f32d6b078f2be110a00734099f1d0724f81c2f295f19bd18cb1d10;
        ntth[22] = 0x09d7005f17810b5823d304da0eff05511f5d08c5158b0b5b2b202b9a17e51048;
        ntth[23] = 0x0c2c07181bbf2b700388077d21482a5e108804870ea3139126fc0e861b5108fe;
        ntth[24] = 0x1f692ef81f02125926be10452ee32e012712224f0e4f06300e7a124f1bff08ea;
        ntth[25] = 0x193616852d1a0a9a26e621a1269906fc171c2121070f2fcc132323931280200e;
        ntth[26] = 0x23f0217704e5273f292f2c39191c20960e5d087c1d2009411ff506ee2c7c1fb8;
        ntth[27] = 0x17b520df133416750bc802a91b920a921ad0103d038816570eed0ee20cbf1ae1;
        ntth[28] = 0x0008060700f81f3b01f815d10e0a2dd71ae81e542ee0025a02d60433269605d7;
        ntth[29] = 0x0810089d0a0d0e230e5d1c8c001908051c491aea1eea1abf0d41032205eb1c8a;
        ntth[30] = 0x160f1b3105330fa9215e03801d2c1fa721d80b531c5027c823dc29e816fb03c8;
        ntth[31] = 0x11de233417a005f402ce16770d8f07e307312835177f130920e906f524bd10a8;

        s2 = new uint256[](32);
        s2[0]  = 0x2fd22f802fc7005c2edb00dc00e1001300922f5a2fdd00892f912fe2001d2f7c;
        s2[1]  = 0x002e01c72fdb2f48010a2fa12f8c002c00522f8400b72e832fa701212f84001a;
        s2[2]  = 0x001b2f4d00b3004900672fff00cd2ef2005c003c00b6002500632f7500342f62;
        s2[3]  = 0x00862f7900232f702fa50033017b00db2fb201942f95005f2faf2fee2fd42fa2;
        s2[4]  = 0x011900242feb2fd72fbd2ffd2ffd01012f322f0b001d009f0176017e000e0094;
        s2[5]  = 0x00082f4a009b2feb00082fcc2fc42f982f93001d2f1c007c2ed500182f1c0096;
        s2[6]  = 0x2f8d00042ffd0030004000d22f7300e9009400022f2b00b92f640013000d2f89;
        s2[7]  = 0x2f852fcd2e6b00382f5c000c2f832eda2f6f2f5d015300272feb001e2f430060;
        s2[8]  = 0x007600932f69017f0109002b01bc2f9300232f0e00442eed00d800952ec12f2c;
        s2[9]  = 0x00cd2ef9004d00902fa200250088000d2fec004b2f9b2eb92f8a2f49004b2f6e;
        s2[10] = 0x003c003c2fa02fa92f9700992fde002900492fde2f9800c1006100762f90000e;
        s2[11] = 0x2f5f007b2fab01ab001f005f2f902ecc00df01892ec02fdc00c02ffc2f830006;
        s2[12] = 0x2fb90118002f2f6d2e3c2f722fcf00df2f5800182f9c00002f7c2fd82fe12f36;
        s2[13] = 0x2ef800172f8400c72fd70083013d2eda2f3e2faa009c2f56012e2ef200130013;
        s2[14] = 0x005f2f5f005a0085005e2f802fe02f6e005300e300dd2f8a2fd300aa2f300063;
        s2[15] = 0x004f00352fb12f4e00522f5f00a100952fa52f502fe02fdd2f8301372fab2ef6;
        s2[16] = 0x004000a2016c00cf2f992e942f2700ed001c000a2fd2008c0003001a2faa0031;
        s2[17] = 0x005c2fea2fe12fd6010d2fd72f54007a2fb82fb02f9f2f632fe100ad2fd32fa3;
        s2[18] = 0x2f80000a00932fa22fba010f00a82f872f2f00152f8c2f7c00012fb800710004;
        s2[19] = 0x2f472f562fe2009a006300872fb100302ec22f032f9300d200dc2fe700162f9c;
        s2[20] = 0x2e8e001f2f852edf2f620090015b2f910088021a001500682f3f00bd002300c8;
        s2[21] = 0x0073000700302f4c2f742fd0001600a2010b2fa900de2f1900642ffa2fc62f89;
        s2[22] = 0x2ebe00a72f4e00a5001c006100242fbc2fa300ab00112f6900272ffc00dd2f60;
        s2[23] = 0x2f7e2edd2ff700f92fa3005a006b2efb00372f7f2e20004d2f242f1c00a3004f;
        s2[24] = 0x00222e7000282fc800bb2f082f182f8a006600cd2eec2ffc00cb2fdd00690068;
        s2[25] = 0x000700ad00d72fb7006d2fac2ff82f6e2fd12fea2fa900eb00d000652f312fa0;
        s2[26] = 0x2f272fb1007f00652f6e001e2ffe2f3600402fdd009300492fee2f39014000ac;
        s2[27] = 0x00672edd00212f560133004b2f600041012e00be00e32fd22fbb2fe92ee12f4b;
        s2[28] = 0x000a00b22fb9003a00752f0b2f72003300e00070004b2ee1005f00b22f372fa1;
        s2[29] = 0x00172f61003e2de2002e008d2f9b001e00e4000e003a2fd32f392ff700510087;
        s2[30] = 0x0052001f00da2f862f262f99012401052f9a00e100372fb82f5e0065003d2f7b;
        s2[31] = 0x00510092000800152f352fef0058008500502fba00832fd92f8c005200a32f5b;

        salt = hex"46e5ab3d8df91f6bed84fbdabbd857d3ebab307e5fbc8eb36f1dfaefdddb59fa31266430184fcfc2";
    }
}
